### ISSUE TITLE
Unable to test the warping module 

### ISSUE THREAD

**Issue by RishiGitH** [bcmi/DCI-VTON-Virtual-Try-On#22]
I am getting issue with  cupy module and it's not part of the conda env yaml file 

when running sh test_VITON.sh i am getting this 
<img width="768" alt="Screenshot 2023-10-16 at 5 28 48 PM" src="https://github.com/bcmi/DCI-VTON-Virtual-Try-On/assets/16270443/33ffc6ce-a769-48c4-b4b3-d96dc1c13d34">

Also my gpu and cuda version is 

<img width="579" alt="Screenshot 2023-10-16 at 5 26 56 PM" src="https://github.com/bcmi/DCI-VTON-Virtual-Try-On/assets/16270443/45f9fe52-8f74-484a-aefc-6dbb7fb52dfc">

Let me know how you got it working for youself . The readme seems to be missing this bit

**Comment by dx777** [comment]
`pip install cupy-cuda12x` in your case

**Comment by RishiGitH** [comment]
@dx777  getting this issue 
`ERROR: Could not find a version that satisfies the requirement cupy-cuda121 (from versions: none)
ERROR: No matching distribution found for cupy-cuda121`

**Comment by dx777** [comment]
@RishiGitH  the packet is named cupy-cuda12x not cuda121

**Comment by RishiGitH** [comment]
@dx777  but then i get this issue if i install cuda 12. I am having a lot of troubles with PF-AFN any idea what could be the issue 

`Traceback (most recent call last):
  File "eval_PBAFN_viton.py", line 11, in <module>
    from models.afwm import AFWM
  File "/home/ubuntu/PF-AFN/PF-AFN_test/models/afwm.py", line 4, in <module>
    from .correlation import correlation
  File "/home/ubuntu/PF-AFN/PF-AFN_test/models/correlation/correlation.py", line 274, in <module>
    @cupy.util.memoize(for_each_device=True)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/cupy/__init__.py", line 921, in __getattr__
    raise AttributeError(f"module 'cupy' has no attribute {name!r}")
AttributeError: module 'cupy' has no attribute 'util'`

**Comment by RishiGitH** [comment]
@dx777  Thanks got this resolved but now I am getting this issue . Is it due to image size ?

`RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/conda/envs/test/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/envs/test/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/envs/test/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ubuntu/PF-AFN/PF-AFN_test/data/cp_dataset.py", line 172, in __getitem__
    parse_map = parse_map.scatter_(0, parse, 1.0)
RuntimeError: Expected index [1, 576, 384] to be smaller than self [20, 512, 384] apart from dimension 0
`

**Comment by RishiGitH** [comment]
@Limbor  do you have any idea ? ^^

**Comment by boya34** [comment]
change
`@cupy.util.memoize`
to
`@cupy.memoize`
might be helpful

**Comment by sanjeevpenupala** [comment]
I am getting the same issue. What is the solution for this cupy problem?
